source 'https://github.com/CocoaPods/Specs.git'

target 'CedarMaps', :exclusive => true do
    pod 'CedarMaps', '~> 0.1.0'
end

target 'Tests', :exclusive => true do
    pod 'CedarMaps', '~> 0.1.0'

  
end
