source 'https://github.com/CocoaPods/Specs.git'

target 'CedarMaps' do
    pod 'CedarMaps', :git => 'http://gitlab.cedar.ir/cedar.studios/cedarmaps-sdk-ios-public.git'
end

target 'Tests' do
    pod 'CedarMaps', :git => 'http://gitlab.cedar.ir/cedar.studios/cedarmaps-sdk-ios-public.git'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_STRICT_OBJC_MSGSEND'] = 'NO'
        end
    end
end